In [1]:
#Q1 
#'to add the two matrices'
import numpy as np
arr = np.array(([4,5,6],[4,5,6],[4,5,6]))
arr1 = np.array(([6,7,8],[6,7,8],[6,7,8]))
result = arr +arr1
print(result)

[[10 12 14]
 [10 12 14]
 [10 12 14]]


In [2]:
#Q2 
#'to multiply two matrices'
import numpy as np
arr = np.array(([4,5,6],[4,5,6],[4,5,6]))
arr1 = np.array(([6,7,8],[6,7,8],[6,7,8]))
result = arr * arr1
print(result)

[[24 35 48]
 [24 35 48]
 [24 35 48]]


In [3]:
#Q3
#program to transpose a matrix
import numpy as np
arr = np.matrix('[10,8,78;9,34,0]')
result = arr.transpose()
print(result)

[[10  9]
 [ 8 34]
 [78  0]]


In [5]:
#Q4
#'to sort words in alphabetic order'
ra = input("enter the string: ")
word = ra.split()
word.sort()
for result in word:
    print(result)
    

enter the string: my name is Bhupesh pandey
Bhupesh
is
my
name
pandey


In [6]:
#Q5
#'program to remove the punctuation'
import re 
ra = input("enter the string: ")
ra = re.sub(r'[^\w\s]','',ra)
print(ra)

enter the string: $bhupesh #is %student ^of *ineuron
bhupesh is student of ineuron
